import { type CSSProperties } from "react";
import { Link } from "react-router-dom";
import { CASES } from "./cases";

/* ------------------------------------------------------------------ */
/*  Reusable style helpers                                             */
/* ------------------------------------------------------------------ */
const container: CSSProperties = {
  maxWidth: 860,
  margin: "0 auto",
  padding: "2rem 1.5rem 4rem",
};

const section: CSSProperties = {
  marginTop: "3rem",
};

const h1Style: CSSProperties = {
  fontSize: "2.2rem",
  fontWeight: 700,
  lineHeight: 1.2,
  marginBottom: "0.5rem",
};

const h2Style: CSSProperties = {
  fontSize: "1.5rem",
  fontWeight: 600,
  marginBottom: "0.75rem",
  borderBottom: "2px solid var(--accent)",
  paddingBottom: "0.25rem",
  display: "inline-block",
};

const h3Style: CSSProperties = {
  fontSize: "1.15rem",
  fontWeight: 600,
  marginTop: "1.5rem",
  marginBottom: "0.5rem",
};

const pStyle: CSSProperties = {
  marginBottom: "1rem",
};

const eqBlock: CSSProperties = {
  background: "var(--code-bg)",
  borderRadius: 6,
  padding: "0.75rem 1rem",
  fontFamily: "var(--font-mono)",
  fontSize: "0.9rem",
  overflowX: "auto",
  margin: "1rem 0",
};

const tableWrap: CSSProperties = {
  overflowX: "auto",
  margin: "1rem 0",
};

const tableStyle: CSSProperties = {
  borderCollapse: "collapse",
  width: "100%",
  fontSize: "0.95rem",
};

const thStyle: CSSProperties = {
  textAlign: "left",
  padding: "0.5rem 0.75rem",
  borderBottom: "2px solid var(--border)",
  fontWeight: 600,
};

const tdStyle: CSSProperties = {
  padding: "0.5rem 0.75rem",
  borderBottom: "1px solid var(--border)",
};

/* ------------------------------------------------------------------ */
/*  App — main landing page                                            */
/* ------------------------------------------------------------------ */
export default function App() {
  return (
    <div style={container}>
      {/* ---- Header ---- */}
      <header>
        <h1 style={h1Style}>Admixture Identifiability</h1>
        <p style={{ ...pStyle, fontSize: "1.1rem", color: "var(--muted)" }}>
          Recovering a latent shape distribution from noisy additive
          observations using rectified flow matching.
        </p>
      </header>

      {/* ---- The Setup ---- */}
      <section style={section}>
        <h2 style={h2Style}>The Setup: Gaussian Bump Model</h2>

        <p style={pStyle}>
          We observe a one-dimensional signal <code>X</code> that is the sum of
          many shifted "bumps." Each bump is a Gaussian-shaped pulse whose
          amplitude and width are drawn from an unknown distribution{" "}
          <strong>π</strong>. A large fraction of the bumps are{" "}
          <em>null</em> — contributing exactly zero — so the signal is sparse.
        </p>

        <h3 style={h3Style}>Shape function (V-binary gating)</h3>
        <p style={pStyle}>
          Each latent mark has a binary gate <code>V ∈ &#123;0, 1&#125;</code>{" "}
          and parameters <code>(ρ, log σ)</code> ∈ ℝ². The shape on the
          integer grid &#123;−L, …, L&#125; is:
        </p>
        <div style={eqBlock}>
          f(x) = V · ρ · exp(−x² / (2 · exp(2·log σ)))
        </div>
        <p style={pStyle}>
          When <code>V=0</code> (null mark), the contribution to X is exactly
          zero and (ρ, log σ) = (0, 0) by convention. When <code>V=1</code>{" "}
          (active mark), ρ is used directly as the amplitude. This clean
          separation avoids the problem where the flow matching loss gets
          inflated by trying to predict arbitrary null-mark parameters (e.g.
          ρ ≈ −10) that don't affect X at all.
        </p>

        <h3 style={h3Style}>Generative process</h3>
        <p style={pStyle}>
          Given parameters (L, T, π), a single observation X ∈ ℝᵀ⁻²ᴸ⁺¹ is
          generated by:
        </p>
        <ol style={{ ...pStyle, paddingLeft: "1.5rem" }}>
          <li>
            For each position t ∈ &#123;0, …, T&#125;, sample (Vₜ, Uₜ) =
            (Vₜ, ρₜ, log σₜ) ∼ π.
          </li>
          <li>
            For each visible position t ∈ &#123;L, …, T−L&#125;, compute Xₜ =
            Σ Vₜ · ρ_τ · exp(−(t−τ)² / (2·exp(2·log σ_τ))).
          </li>
        </ol>

        <h3 style={h3Style}>Goal</h3>
        <p style={pStyle}>
          <strong>Estimate π from samples of X alone.</strong> The latent
          (V, U) marks are never observed. In particular, we want to recover
          the null probability — the fraction of marks where V=0.
        </p>
      </section>

      {/* ---- What We Do ---- */}
      <section style={section}>
        <h2 style={h2Style}>What We Do: Two-Flow Rectified Flow Matching</h2>

        <p style={pStyle}>
          We train <strong>two flow matching networks</strong> simultaneously:
        </p>
        <ol style={{ ...pStyle, paddingLeft: "1.5rem" }}>
          <li>
            <strong>V-flow</strong> — a rectified flow matching network that
            learns the <em>joint</em> distribution of the binary gate vector V
            given X.  At inference the ODE output is rounded to &#123;0, 1&#125;.
            Unlike independent logits, flow matching captures correlations
            between positions.
          </li>
          <li>
            <strong>U-flow</strong> — a conditional rectified flow matching
            network that maps noise to <code>U ∈ ℝ⁽ᵀ⁺¹⁾ˣ²</code> given (X, V).
            Both the interpolated state, target velocity, and predicted velocity
            are <em>masked</em> at V=0 positions — not just the loss — so the
            network never sees or produces non-zero values at null positions.
          </li>
        </ol>

        <h3 style={h3Style}>Phase I — Warm-up</h3>
        <p style={pStyle}>
          Train both networks on (X, V, U) triples sampled from an initial guess
          π̂. Each gradient step uses <em>freshly simulated</em> data.
        </p>

        <h3 style={h3Style}>Phase II — Iterative refinement (bootstrap)</h3>
        <ol style={{ ...pStyle, paddingLeft: "1.5rem" }}>
          <li>
            Draw X samples from the <strong>true</strong> model (L, T, π).
          </li>
          <li>
            Predict V̂ using the V-flow network (integrate ODE, round to
            &#123;0, 1&#125;; stop-gradient).
          </li>
          <li>
            Infer Û using the U-flow conditioned on V̂ (stop-gradient).
            Null positions (V̂=0) get U=(0, 0).
          </li>
          <li>
            Define π̂ as the empirical distribution over (V̂, Û).
          </li>
          <li>
            Train both models on fresh (X, V, U) drawn from this updated π̂.
          </li>
        </ol>
        <p style={pStyle}>
          Phase II restarts both optimisers from scratch — fresh cosine learning
          rate schedules and fresh Adam moments. An <strong>oracle</strong> pair
          of models is trained in parallel on ground-truth (X, V, U) from the
          true π as a performance reference.
        </p>

        <h3 style={h3Style}>Key insight: two flows with masked dynamics</h3>
        <p style={pStyle}>
          The V-flow learns the <em>joint</em> distribution of the binary gate
          vector — capturing correlations between positions that independent
          logits miss.  The U-flow masks the interpolated state, target velocity,
          and predicted velocity at V=0 positions (not just the loss), ensuring
          the network never sees or produces non-zero values at null positions.
        </p>
      </section>

      {/* ---- Runs ---- */}
      <section style={section}>
        <h2 style={h2Style}>Experiment Runs</h2>

        <p style={pStyle}>
          Each run uses the same ground-truth distribution (P(V=0) = 0.95,
          two-component Gaussian mixture for U | V=1) but varies the
          initial guess <strong>π̂</strong> — both P̂(V=0) and the
          distribution on U.
        </p>

        <div style={tableWrap}>
          <table style={tableStyle}>
            <thead>
              <tr>
                <th style={thStyle}>Run</th>
                <th style={thStyle}>P̂(V=0)</th>
                <th style={thStyle}>π̂ U-components</th>
                <th style={thStyle}>Details</th>
              </tr>
            </thead>
            <tbody>
              {CASES.map((c) => (
                <tr key={c.slug}>
                  <td style={tdStyle}>
                    <Link to={`/runs/${c.slug}`}>{c.label}</Link>
                  </td>
                  <td style={tdStyle}>{c.nullProbInit}</td>
                  <td style={tdStyle}>
                    {c.pihatComponents.map((comp, i) => (
                      <span key={i}>
                        {i > 0 && " + "}
                        {comp.weight}× 𝒩(μ=({comp.mean.join(", ")}),
                        σ=({comp.std.join(", ")}))
                      </span>
                    ))}
                  </td>
                  <td style={tdStyle}>
                    <Link to={`/runs/${c.slug}`}>View →</Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* ---- Footer ---- */}
      <footer
        style={{
          marginTop: "4rem",
          padding: "1.5rem 0",
          borderTop: "1px solid var(--border)",
          fontSize: "0.85rem",
          color: "var(--muted)",
          textAlign: "center",
        }}
      >
        <p>
          Source:{" "}
          <a href="https://github.com/prob-ml/admixture-identifiability">
            prob-ml/admixture-identifiability
          </a>
        </p>
      </footer>
    </div>
  );
}
